# Generated by Django 4.2.5 on 2023-09-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.CharField(max_length=9, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('GBA', models.BooleanField()),
            ],
        ),
    ]
